/* Generated by Together */

package com.mpc.gui;

import java.math.BigDecimal;
import java.util.Observable;

import com.mpc.Util;
import com.mpc.sequencer.TimeSignature;

public class UserDefaults extends Observable {

	private int[] padNotes = { 37, 36, 42, 82, 40, 38, 46, 44, 48, 47, 45, 43, 49, 55, 51, 53, 54, 69, 81, 80, 65, 66,
			76, 77, 56, 62, 63, 64, 73, 74, 71, 39, 52, 57, 58, 59, 60, 61, 67, 68, 70, 72, 75, 78, 79, 35, 41, 50, 83,
			84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98 };

	private int diskDevice;
	private int autoLoadType;
	private BigDecimal tempo;
	private boolean loop;
	private int bus;
	private int deviceNumber;
	private int pgm;
	private int velo;
	private boolean recordingModeMulti;
	private String sequenceName;
	private String[] trackNames;
	private int lastBar;

	private TimeSignature timeSig;
	private String[] deviceNames;

	public UserDefaults() {

		bus = 1;
		tempo = new BigDecimal("120.0");
		velo = 100;
		pgm = 0;
		recordingModeMulti = false;
		loop = true;
		deviceNumber = 0;
		sequenceName = "Sequence";
		trackNames = new String[64];
		for (int i = 0; i < 64; i++)
			trackNames[i] = "Track" + "-" + Util.padLeft2Zeroes(i + 1);
		lastBar = 1;
		timeSig = new TimeSignature();
		timeSig.setNumerator(4);
		timeSig.setDenominator(4);
		deviceNames = new String[33];
		deviceNames[0] = "        ";
		for (int i = 1; i < 33; i++) {
			deviceNames[i] = "Device" + Util.padLeft2Zeroes(i);
		}

		autoLoadType = 0;
		diskDevice = 0;
	}

	public String getDeviceName(int i) {
		return deviceNames[i];
	}

	void setDiskDevice(int i) {

		if (i < 0 || i > 8) return;

		diskDevice = i;

		setChanged();
		notifyObservers("diskdevice");
	}

	void setAutoLoadType(int i) {

		if (i < 0 || i > 3) return;

		autoLoadType = i;

		setChanged();
		notifyObservers("autoloadtype");
	}

	public void setTempo(BigDecimal i) {
		double j = i.doubleValue();
		if (j < 30.0) i = new BigDecimal("30.0");
		if (j > 300.0) i = new BigDecimal("300.0");
		tempo = i;
		setChanged();
		notifyObservers("tempo");
	}

	public void setLoop(boolean b) {
		loop = b;
		setChanged();
		notifyObservers("loop");
	}

	public BigDecimal getTempo() {
		return tempo;
	}

	public int getDiskDevice() {
		return diskDevice;
	}

	public int getAutoLoadType() {
		return autoLoadType;
	}

	public boolean isRecordingModeMulti() {
		return recordingModeMulti;
	}

	public void setBus(int i) {

		if (i < 0 || i > 4) return;

		bus = i;
		setChanged();
		notifyObservers("tracktype");
	}

	public void setDeviceNumber(int i) {

		if (i < 0 || i > 33) return;

		deviceNumber = i;
		setChanged();
		notifyObservers("devicenumber");
	}

	public void setRecordingModeMulti(boolean b) {

		recordingModeMulti = b;
		setChanged();
		notifyObservers("recordingmode");
	}

	public boolean isLoopEnabled() {
		return loop;
	}

	public int getBus() {
		return bus;
	}

	public int getDeviceNumber() {
		return deviceNumber;
	}

	public int getPgm() {
		return pgm;
	}

	public int getVeloRatio() {
		return velo;
	}

	public void setLastBar(int i) {
		if (i < 0 || i > 998) return;
		lastBar = i;
		setChanged();
		notifyObservers("bars");
	}

	public void setPgm(int i) {
		if (i < 0 || i > 128) return;
		pgm = i;
		setChanged();
		notifyObservers("pgm");
	}

	public void setVelo(int i) {
		if (i < 1) i = 1;
		if (i > 200) i = 200;
		velo = i;
		setChanged();
		notifyObservers("velo");
	}

	public String getSequenceName() {
		return sequenceName;
	}

	public String getTrackName(int i) {
		return trackNames[i];
	}

	public int getLastBarIndex() {
		return lastBar;
	}

	public TimeSignature getTimeSig() {
		return timeSig;
	}

	public int[] getPadNotes() {
		return padNotes;
	}

	public void setPadNotes(int[] ia) {
		padNotes = ia;
	}

	public byte getTrackStatus() {
		return 6;
	}

	public void setDeviceName(int i, String s) {
		deviceNames[i] = s;
	}

	public void setSequenceName(String name) {
		sequenceName = name;
	}

	public void setTimeSig(int num, int den) {
		TimeSignature ts = new TimeSignature();
		ts.setNumerator(num);
		ts.setDenominator(den);
	}

	public void setTrackName(int i, String s) {
		trackNames[i] = s;
	}
}
