/* Generated by Together */

package com.mpc.sequencer;

public class ChannelPressureEvent extends Event {
    private int channelPressureValue;

	public void setAmount(int i) {
		if (i<0||i>127) return;
        channelPressureValue = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getAmount() {
        return channelPressureValue;
    }
}
