/* Generated by Together */

package com.mpc.sequencer;

public class ControlChangeEvent extends Event {
    private int controllerNumber;
    private int controllerValue;

	public void setController(int i) {
		if (i<0||i>127) return;
        controllerNumber = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getController() {
        return controllerNumber;
    }

	public void setAmount(int i) {
		if (i<0||i>127) return;
		controllerValue = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getAmount() {
        return controllerValue;
    }

}
