/* Generated by Together */

package com.mpc.sequencer;

public class DurationEvent extends Event {
    private int duration;
   
    public DurationEvent() {
    	duration = -1;
    }
    
    public void setDuration(int i) {
    	if (i<0||i>9999) return;
        duration = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getDuration() {
        return duration;
    }
}
