/* Generated by Together */

package com.mpc.sequencer;

import javax.sound.midi.ShortMessage;

public class MidiClockEvent extends Event {
 
	private int status;

	private ShortMessage shortMessage;
	
	public MidiClockEvent(int status) {
		this.status = status;
		shortMessage = new ShortMessage();
	}
	
	public int getStatus() {
		return status;
	}
	
	public ShortMessage getShortMessage() {
		return shortMessage;
	}

	public void setStatus(int i) {
		status = i;
	}
	
}
