/* Generated by Together */

package com.mpc.sequencer;

public class PolyPressureEvent extends Event {
    private int note;
    private int polyPressureValue;

	public void setNote(int i) {
		if (i<0||i>127) return;
        note = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getNote() {
        return note;
    }

	public void setAmount(int i) {
		if (i<0||i>127) return;
		polyPressureValue = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getAmount() {
        return polyPressureValue;
    }
}
