/* Generated by Together */

package com.mpc.sequencer;

public class ProgramChangeEvent extends Event {
    private int programChangeValue;

	public void setProgram(int i) {
		if (i<1||i>128) return;
        programChangeValue = i;
        setChanged();
        notifyObservers("stepeditor");
    }

    public int getProgram() {
        return programChangeValue;
    }
}
